"""initial migration

Revision ID: 1fb091960251
Revises: 
Create Date: 2025-04-09 00:12:28.534735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb091960251'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('execution_type', sa.Enum('SYNC', 'ASYNC', name='executiontypeenum'), nullable=False, server_default="SYNC"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'execution_type')
    # ### end Alembic commands ###
